SEASONING_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export SEASONING_HOME

SEASONING_VERSION=*SEASONING_VERSION*
export SEASONING_VERSION

PATH=$PATH:$SEASONING_HOME/bin
export PATH
